# To run prometheus and grafana on another machine and grab metrics from the pi, can use this
# though these don't add too much memory burden even on the 512MB pilite
version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./targets.json:/etc/prometheus/targets.json
    ports:
      - '19090:9090'
  
  grafana:
    user: '1000'
    image: grafana/grafana:latest
    ports: 
      - '13030:3000'

networks:
    default:
      ipam:
        config:
          - subnet: 10.6.9.0/28