{
 "title": "Object Detector Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Objects Seen",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nsbeetle_objects_seen_total[1m])",
     "legendFormat": "{{class}}, {{confidence}}"
    }
   ]
  },
  {
   "title": "Objects Seen (>Med/High Conf)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (class) (rate(nsbeetle_objects_seen_total{confidence!='Low'}[20s]))",
     "legendFormat": "{{class}}, {{confidence}}"
    }
   ]
  },
  {
   "title": "Camera images captured / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nsbeetle_camera_images_captured_total[5m])"
    }
   ]
  }
 ]
}